[workspace]
channels = ["conda-forge"]
name = "bluesky_pdf"
platforms = [{ platform = "linux-64", glibc = "2.17" }]
version = "2026.2.0"

# [system-requirements]
# libc = "2.17"

[feature.profile.dependencies]
bluesky-base = "==1.15.1"
# bluesky-queueserver = "*"
matplotlib-base= ">=3.10"
networkx = ">=3.4.2,<4"
nslsii = "==0.11.8"
numpy = "*"
ophyd = ">=1.11.0"
pyepics = "*"
python = ">=3.12,<3.14"
semver = ">=3.0.4,<4"
# bluesky-darkframes = ">=0.6.0,<0.7"
# xpdan = ">=0.8.2,<0.9"
lmfit = ">=1.3.4,<2"
# databroker = "==2.0.0"
# bluesky-tiled-plugins = ">=2.0.11"
tifffile = ">=2025.5.10,<2026"
setuptools = "<81"
hdf5-external-filter-plugins = ">=0.1.0,<0.2"
blosc-hdf5-plugin = ">=1.0.1,<2"
epicscorelibs = ">=7.0.7.99.1.1,<8"
tiled = ">=0.2.9,<0.3"
# xpdacq = "==1.0.0"
aioca = ">=2.0,<3"

[feature.profile.pypi-dependencies]
pvxslibs = ">=1.3.2, <2"
# diffpy-pdfgetx = { path = "/opt/diffpy.pdfgetx-2.4.0/py312/diffpy_pdfgetx-2.4.0-cp312-cp312-linux_x86_64.whl" }
# pdfstream = { git = "https://github.com/NSLS-II-PDF/pdfstream.git", rev="v0.5.x" }
pdftools = { git = "https://github.com/NSLS2/pdftools", rev="main" }
bluesky-tiled-plugins = { git = "https://github.com/bluesky/bluesky-tiled-plugins", branch="main" }


[feature.terminal.dependencies]
ipython = ">=9.5.0"
pyside6 = "*"
numpy = ">2"
pandas = "*"
jupyterlab = "*"


[workspace.conda-pypi-map]
conda-forge = {
    mapping = {
        bluesky-tiled-plugins = false
    }
}


# [feature.terminal.tasks]
# start = "unset SESSION_MANAGER PYTHONPATH && MPLBACKEND=qtagg ipython --profile-dir=$HOME/.ipython/profile_$BS_PROFILE"
# pvs = "ipython --profile-dir=. -c 'get_pv_types(); exit()'"


[environments]
terminal = {features=["profile", "terminal"], solve-group="profile"}
